name: Jira Release
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo '${{github.event.head_commit.message}}'

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9
        
      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
        #run: echo "TAG=1.0.1" >> $GITHUB_ENV
      - name: 버전 태그 체크
        run: echo "${{ env.TAG }}"
      - name: Release & Tag 생성
        #if: github.event.pull_request.merged == true
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
      
