name: Jira Release
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo '${{github.event.head_commit.message}}'
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9
        
      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ github.event.head_commit.message }}' | egrep -0 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
        #run: echo "TAG=1.0.1" >> $GITHUB_ENV
      - name: 버전 태그 체크
        run: echo "${{ env.TAG }}"
      - name: Release & Tag 생성 단계
        #if: github.event.pull_request.merged == true
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allow_duplicate: true
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
      - name: Jira Release
        id: release
        uses: PRNDcompany/jira-release@v1.2
        with:
          domain: 'istay-test1'
          project: 'I20'
          version: 'DEV ${{ env.TAG }}'
          auth-token: 'a2tpbUBpc3RheS5pbzppVU55ZUNwV1RXR2xuZWs1eXlodEJGMjc='
      - name: Print New Version
        run: |
          echo ${{ steps.release.outputs.new-version }}
