name: Jira Release
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo '${{github.event.head_commit.message}}'
      - name: Extract version name
        run: echo "TAG=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
        id: extract_version_name
      - name: Jira Release
        id: release
        uses: PRNDcompany/jira-release@v1.3
        with:
          domain: https://istay-test1.atlassian.net
          project: I20
          version: BACK ${{ env.TAG }}
          auth-token: a2tpbUBpc3RheS5pbzppVU55ZUNwV1RXR2xuZWs1eXlodEJGMjc=
      - name: Print New Version
        run: |
          echo ${{ steps.release.outputs.new-version }}
